SELECT COUNT(*) AS FEMALE_PASSENGER_COUNT FROM AIRLINE
WHERE GENDER = 'Female';

SELECT COUNT(*) AS BUSINESS_CLASS_PASSENGER_COUNT FROM AIRLINE
WHERE CLASS = 'Business';

SELECT COUNT(*) AS ECO_CLASS_PASSENGER_COUNT FROM AIRLINE
WHERE CLASS = 'Eco';

SELECT COUNT(*) AS AGE_BELOW_13_PASSENGER_COUNT FROM AIRLINE
WHERE AGE < 13;

SELECT COUNT(*) AS AGE_ABOVE_16_BUSINESS_CLASS_PASSENGER_COUNT FROM(
    SELECT ID FROM AIRLINE
    WHERE AGE > 16 AND CLASS = 'Business'
) AS SUB;