SELECT COUNT(*) FROM AIRLINE
WHERE GENDER = 'Female';

SELECT COUNT(*) FROM AIRLINE
WHERE CLASS = 'Business';

SELECT COUNT(*) FROM AIRLINE
WHERE CLASS = 'Eco';

SELECT COUNT(*) FROM AIRLINE
WHERE AGE < 13;

SELECT COUNT(*) FROM AIRLINE
WHERE AGE > 16 AND CLASS = 'Business';