SELECT  
    COUNT(CASE WHEN GENDER = 'Female' THEN 1 END) FEMALE_PASSENGERS,
    COUNT(CASE WHEN CLASS = 'Business' THEN 1 END) BUSINESS,
    COUNT(CASE WHEN CLASS = 'Eco' THEN 1 END) ECONOMY,
    COUNT(CASE WHEN AGE < 13 THEN 1 END) CHILDREN_BELOW_13,
    COUNT(CASE WHEN AGE > 16 AND CLASS = 'Business' THEN 1 END) BUSINESS_WITH_AGE_ABOVE_16
FROM    
    airline;