SELECT  
    COUNT(CASE WHEN GENDER = 'Female' THEN 1 END) FEMALEPASSENGERS,
    COUNT(CASE WHEN CLASS = 'Business' THEN 1 END) BUSINESS,
    COUNT(CASE WHEN CLASS = 'Eco' THEN 1 END) ECONOMY,
    COUNT(CASE WHEN AGE < 13 THEN 1 END) CHILDREN,
    COUNT(CASE WHEN AGE > 16 AND CLASS = 'Business' THEN 1 END) BUSINESSAGE16
FROM    
    airline;



